AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs18.x

Resources:
  # Lambda for streaming data (SSE) + cookie handling
  SendStreamFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handler.handler
      CodeUri: .
      Environment:
        Variables:
          LOG_BUCKET_NAME: !Ref LogBucket
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref LogBucket
      Events:
        SendStreamApi:
          Type: Api
          Properties:
            Path: /sendStream
            Method: GET
            RestApiId: !Ref MyApi
        SendCookieApi:
          Type: Api
          Properties:
            Path: /sendCookie
            Method: GET
            RestApiId: !Ref MyApi
        htmlApi:
          Type: Api
          Properties:
            Path: /html
            Method: GET
            RestApiId: !Ref MyApi
        ReadCookieApi:
          Type: Api
          Properties:
            Path: /readCookie
            Method: GET
            RestApiId: !Ref MyApi

  # Lambda for serving the HTML page
  ReceiveStreamFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handler.receiveStream
      CodeUri: .
      Environment:
        Variables:
          LOG_BUCKET_NAME: !Ref LogBucket
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref LogBucket
      Events:
        ReceiveStreamApi:
          Type: Api
          Properties:
            Path: /receiveStream
            Method: GET
            RestApiId: !Ref MyApi

  # Shared API Gateway for all endpoints
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: StreamingApi
      StageName: Prod
      Cors:
        AllowMethods: "'GET'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  # S3 Bucket for logs
  LogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-log-bucket"
      AccessControl: Private

Outputs:
  WebEndpoint:
    Description: "Full URL to access the HTML viewer"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/receiveStream"

  SendStreamEndpoint:
    Description: "Streaming endpoint for client (SSE)"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/sendStream"

  SendCookieEndpoint:
    Description: "Endpoint to send a cookie"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/sendCookie"

  ReadCookieEndpoint:
    Description: "Endpoint to read a cookie"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/readCookie"

  LogBucketName:
    Description: "S3 bucket name for storing logs"
    Value: !Ref LogBucket
